# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '/'
    weight: 10
    
  - name: Publications
    url: '#publications'
    weight: 20
    
  - name: Grants and Awards
    url: '#grants-awards'
    weight: 30
    
  - name: Services
    url: '#services'
    weight: 40
    
  - name: Codes
    url: '#codes'
    weight: 50
    
  - name: Creative
    url: '#creative'
    weight: 60
    
  - name: Media and Talks
    url: '#media'
    weight: 70
    
  - name: Blog
    url: '#blog'
    weight: 80